# Generated by Django 5.2.5 on 2025-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('clf', 'CLF'), ('isis', 'ISIS'), ('diamond', 'Diamond')], max_length=16)),
                ('range_key', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('spec_hash', models.CharField(db_index=True, max_length=64)),
                ('spec_json', models.JSONField()),
                ('labels', models.JSONField()),
                ('kwh', models.JSONField()),
                ('total_kwh', models.FloatField()),
                ('start_unix', models.BigIntegerField()),
                ('end_unix', models.BigIntegerField()),
                ('step_seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'range_key', 'spec_hash', '-updated_at'], name='main_projec_source_471990_idx')],
            },
        ),
    ]
