# Generated by Django 5.2.5 on 2025-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectenergy',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddConstraint(
            model_name='projectenergy',
            constraint=models.CheckConstraint(condition=models.Q(('total_kwh__gte', 0)), name='total_kwh_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='projectenergy',
            constraint=models.CheckConstraint(condition=models.Q(('step_seconds__gt', 0)), name='step_seconds_pos'),
        ),
        migrations.AddConstraint(
            model_name='projectenergy',
            constraint=models.CheckConstraint(condition=models.Q(('start_unix__lte', models.F('end_unix'))), name='start_le_end'),
        ),
    ]
