# Generated by Django 5.2.5 on 2025-08-26 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectenergy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('clf', 'CLF'), ('isis', 'ISIS'), ('diamond', 'Diamond')], db_index=True, help_text='Project/source this workspace belongs to (matches views).', max_length=16)),
                ('instrument', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(default='Workspace', max_length=128)),
                ('owner', models.CharField(blank=True, default='', max_length=128)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('runtime_seconds', models.BigIntegerField(default=0)),
                ('total_kwh', models.FloatField(default=0.0)),
                ('total_kg', models.FloatField(default=0.0)),
                ('idle_kwh', models.FloatField(default=0.0)),
                ('idle_kg', models.FloatField(default=0.0)),
                ('avg_ci_g_per_kwh', models.FloatField(blank=True, null=True)),
                ('last_ci_g_per_kwh', models.FloatField(blank=True, null=True)),
                ('last_sampled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source', '-updated_at'], name='main_worksp_source_b81672_idx'), models.Index(fields=['instrument', '-updated_at'], name='main_worksp_instrum_571b14_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('runtime_seconds__gte', 0)), name='ws_runtime_nonneg'), models.CheckConstraint(condition=models.Q(('total_kwh__gte', 0)), name='ws_total_kwh_nonneg'), models.CheckConstraint(condition=models.Q(('total_kg__gte', 0)), name='ws_total_kg_nonneg'), models.CheckConstraint(condition=models.Q(('idle_kwh__gte', 0)), name='ws_idle_kwh_nonneg'), models.CheckConstraint(condition=models.Q(('idle_kg__gte', 0)), name='ws_idle_kg_nonneg')],
            },
        ),
    ]
