# Generated by Django 5.2.5 on 2025-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('clf', 'CLF'), ('isis', 'ISIS'), ('diamond', 'Diamond')], db_index=True, max_length=16)),
                ('instrument', models.CharField(db_index=True, max_length=64)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('avg_ci_g_per_kwh', models.FloatField()),
                ('kwh_per_hour', models.FloatField()),
                ('kg_per_hour', models.FloatField()),
                ('tdp_spec', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source', 'instrument', '-updated_at'], name='main_instru_source_c38d0b_idx')],
            },
        ),
    ]
