"""
WSGI config for Ada mock project.

It exposes the WSGI callable as a module-level variable named ``application``.

This file mirrors the default generated by Django's ``startproject`` command
to enable deployment using WSGI servers such as Gunicorn or uWSGI. The
application defined here won't run until Django is installed in the
environment. See ``manage.py`` for more information.
"""

import os
from django.core.wsgi import get_wsgi_application  # type: ignore


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ada_project.settings')

application = get_wsgi_application()
