#!/usr/bin/env python
"""
Management utility for the Ada mock Django project.

This script mirrors the default `manage.py` generated by Django's
project template. It sets the appropriate settings module and then
delegates to Django's command‐line execution engine. Because this
repository contains a mocked interface only, the script won't run
successfully without Django installed in your environment. Users who
clone this repository should ensure Django is available before
executing any manage.py commands.
"""

import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ada_project.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()